### ISSUE TITLE
Integration loses connection to Digitalstrom server (DSS)

### ISSUE THREAD

**Issue by tmycgn** [Mat931/digitalstrom-homeassistant#12]
Hi,

The integration often loses the connection after a few days, I suspect an authentication timeout according to the log. Does anyone have an idea or can confirm this? The solution is always to reload the integration, then it works again for a few days.

BR Thomas

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:240
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 21:28:20 (1 occurrences)
Last logged: 21:28:20

[140082199918912] not logged in
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 240, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 628, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/digitalstrom/light.py", line 128, in async_turn_on
    await self.client.request(
  File "/config/custom_components/digitalstrom/api/client.py", line 140, in request
    data = await self._request_raw(url, dict(token=self._session_token))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/digitalstrom/api/client.py", line 79, in _request_raw
    raise InvalidAuth(message)
custom_components.digitalstrom.api.exceptions.InvalidAuth: not logged in
```

**Comment by Mat931** [comment]
Hi,

does this only happen once or on every request afterwards? The authentication works with session tokens which become invalid after Home Assistant makes no requests to DS for 60 seconds (i think). This timeout is tracked by my integration and a new token is requested if needed (if there were no requests made in the last 50 seconds). To try and fix the issue I'm now saving the timestamp only after a request is completed. This should have two effects: If a request fails then no timestamp is saved and the duration of the request is not counted towards the 50 seconds.

To test if the fix works, please install the 'main' version of this integration until v0.0.8 is released.

Best Regards

**Comment by Mat931** [comment]
In HACS kann die Integration über die 3 Punkte oben rechts mit "Erneut herunterladen" neu installiert werden. Dabei einfach als Version 'main' auswählen und anschließend HA neu starten :)

**Comment by tmycgn** [comment]
Ah... wieder was gelernt... :) Erledigt, beobachte es mal. Danke für den ad-hoc Einsatz. :)

**Comment by Mat931** [comment]
Hi @tmycgn ,
ist der Verbindungsfehler nochmal vorgekommen?

MfG

**Comment by tmycgn** [comment]
Hi, sorry, meine Antwort stand noch auf er Todo. :) Ja, die Änderung hat tatsächlich bewirkt dass es nicht mehr zu Verbindungsproblemen kommt. Ich musste seit dem Update den Adapter kein einziges Mal mehr neu laden, vielen Dank Dir!! Issue kann somit geschlossen werden.

**Comment by tmycgn** [comment]
Bin für alles zu haben, fänd ich super!! :) Hätte auch noch Ideen und kleinere Sachen, wollte ich nochmal in Ruhe zusammenfassen. Main Version installiere ich gleich!

**Comment by Mat931** [comment]
Hier der Link zum Discord: https://discord.gg/uTDweuNnHq
