### ISSUE TITLE
Invalid authentication

### ISSUE THREAD

**Issue by M0nteytime** [Mat931/digitalstrom-homeassistant#13]
Hey.

I just can´t get the configuration to run. I added it to HA and also have it running. But I can´t get the connection to the instance of digitalstrom. 
It always claims:  Invalid authentication

I have checked also with firefox, if this solves my issue. Still the same. 
In digitalstrom I can see, that there is a request happening in "Zugriffsherausforderungen". Aceppting the prior does not help, as the token is each time different. What do I do wrong here?

Attached my screens with the SHA256 fingerprint.

SHA: 4E:1C:D8:1C:26:7C:E2:03:6B:DD:09:EE:02:83:DB:F0:05:A4:93:8E:A4:4E:F9:CE:E0:AC:2A:BD:A0:C7:41:4E

I also tried the direct IP and the "dss.local". Both with the same result. 

Any kind of advise is highly appreciated if I forgot anything or if I am just to nooby for it. :D

PS: The invalid authentication happened with the old and the newly released version of today.
PPS: Ignore does not work either...

![Screenshot 2024-02-23 220934](https://github.com/Mat931/digitalstrom-homeassistant/assets/160074848/3359022a-9151-44e7-b0e1-a3d81b9bb034)
![Screenshot 2024-02-23 221105](https://github.com/Mat931/digitalstrom-homeassistant/assets/160074848/6895e5cd-d0ab-4bca-a259-2c3e71d3bc2a)
![Screenshot 2024-02-23 221229](https://github.com/Mat931/digitalstrom-homeassistant/assets/160074848/a152ad6c-b288-4e49-87d7-d54ff697ba12)

**Comment by M0nteytime** [comment]
Okay. So I changed the password. I had a created one that was either too long or due to having symbols, not supported. 

Now it works. Thanks! And sorry for the bother.

**Comment by Mat931** [comment]
Could you tell me the symbols that cause the problem?

**Comment by M0nteytime** [comment]
Hey. 
Will test and let you know in some days. Right now crowded with RL.

**Comment by M0nteytime** [comment]
So. The "#" was not working in the password. The other symbols I have where working: "%*"
Hope this helps.

**Comment by Mat931** [comment]
Special characters in the password should be working in the next release (v0.0.9).
