### ISSUE TITLE
Home Automation

### ISSUE THREAD

**Issue by Adwenger** [Mat931/digitalstrom-homeassistant#15]
[DS_Homeassistant.docx](https://github.com/Mat931/digitalstrom-homeassistant/files/14735428/DS_Homeassistant.docx)
Dear all

I went through all the steps decribed in this page
https://github.com/Mat931/digitalstrom-homeassistant/blob/main/README_de.md?fbclid=IwAR2jpgkmphbz3Jtj06mWhVyrF_SkYBHuwKZ7seNcKZvqmkxAal4hhH0CqJM

I am got ask do you want to configute digitalstrom. But unable to do so. Got the message config flow could not be loaded. Invalid handler specified.
Any ideas what I am mising?
The Installation is unable to find my DSS20 as well.

Thanks for your support
r Adrian
adrian.wenger@awaz.ch

**Comment by Adwenger** [comment]
HACS Installation was succes. Congratulations, you're all set!

**Comment by Mat931** [comment]
There might be a problem with your installation. Please check for a solution here: https://community.home-assistant.io/t/hacs-installing-problem-via-integration-error-config-flow-could-not-be-loaded/314501
