### ISSUE TITLE
Digitalstrom DSM20 

### ISSUE THREAD

**Issue by Bjoernhomeassistant** [Mat931/digitalstrom-homeassistant#16]
With the DSM20 IT IS possible to measure the Power of the Solar Panel. It ist negativ measure. Is this also in Home assisant possible? Thank you in advance. Kind regards. Bjoern

**Comment by Mat931** [comment]
I haven't found a way to read that data from DS. In the [API documentation](https://developer.digitalstrom.org/Architecture/dss-json.pdf) there are two methods of reading energy meter data: getConsumption and getEnergyMeterValue. My integration is already using both of them. Maybe you can find out more information.

**Comment by Bjoernhomeassistant** [comment]
Hi, Update from Digitalstrom Support. vielen Dank für Ihre Anfrage. Es tut mir Leid Ihnen mitzuteilen, das die API nicht mehr gepflegt und auch nicht mehr supportet wird.Neben den Metern werden wir aber als weitere Schnittstelle für die Übertragung von Energiedaten bis Ende Mai eine neue Server FW veröffentlichen, welche die Nutzer dann in die Lage versetzt Daten von bis zu 5 Modbus Schnittstellen in digitalSTROM zu übertragenund visuell Sichtbar zu machen.  Unterstützt werden zum Start folgende Hersteller.Wahrscheinlich kommt zu einem späteren Zeitpunkt noch Modbus IP hinzu. Ich hoffe Ihnen hilft diese Information Ihre Konfiguration umzusetzen.Sorry ist in German.Gesendet von Outlook für Android

**Comment by Bjoernhomeassistant** [comment]
Hi , I ask again the Support of Digitalstrom. No good News. It is not possible to ready Out the measure data from the dsm20 which measure the produced power of the solar panels. I looked in the Data of the Digitalstrom of DSM20, the difference that the consumation Power ist thank true and not false. So I have to look for another solution BG Björn Gesendet von Outlook für Android
