### ISSUE TITLE
[OFFTOPIC] Meter IEC62056-21 Mode D

### ISSUE THREAD

**Issue by aquaticus** [Mat931/digitalstrom-homeassistant#2]
Hi @Mat931 

sorry to post here I could not find a way to contact you.

Some time ago we shared information regarding your electric meter. I added support for it to https://github.com/aquaticus/esphome-iec62056

Could you please tell me what's the meter type and brand? I try to compile a list of supported meters.

**Comment by Mat931** [comment]
@aquaticus Hi! I contacted you on Discord. If that answers your question could you close the issue?
