### ISSUE TITLE
Fenster Status bei mit leider falsch

### ISSUE THREAD

**Issue by BA2000** [Mat931/digitalstrom-homeassistant#3]
Hallo wo kann ich den Status offen/geschlossen für die Fenster konfigurieren. Leider ist da bei DS mit meinen Enocen über die Plan44 angebundenen Sensoren folgender Sachverhalt: 

1 = open
2 = closed

Darum wir bei mir der Status vom Fenster als geschlossen dargestellt, obwohl das Fenster offen ist und umgekehrt.

Kann ich das irgendwo konfigurieren? 

MfG BA2000

**Comment by Mat931** [comment]
Könnten Sie testen, ob der Fehler mit Version 0.0.4 behoben wurde? Falls nicht, teilen Sie mir bitte die in Home Assistant angezeigten Modellnummern der betroffenen Geräte mit.
MfG

**Comment by BA2000** [comment]
Hi Mat931,

DANKE, Fehler behoben! Super!

Mfg BA2000 

Am 8. Dezember 2023 19:38:09 MEZ schrieb Mat931 ***@***.***>:
