### ISSUE TITLE
Thermostat Werte

### ISSUE THREAD

**Issue by BA2000** [Mat931/digitalstrom-homeassistant#4]
Hi, mir ist aufgefallen, dass ich jetzt bei vielen von meinen 191 Etnitäten ein 'wiederhergestllt' Status em Ende der Zeile sehe.
Wenn ich auf das Icon klicke bekomme ich diese Meldung: " Diese Entität wird nicht mehr von der Integration digitalstrom bereitgestellt. Wenn die Entität nicht mehr verwendet wird, lösche sie in den Einstellungen. "

Wie kann ich das beheben?
Es sind fehlende Werte von Thermostaten, Fenstersensoren, Temperatur, Feuchtigkeit.
Soll ich dir  irgendwelche Logs zukommen lassen?

Gruß BA2000

**Comment by Mat931** [comment]
Die Problematik mit den fehlendenden Entitäten wurde auch schon in https://github.com/Mat931/digitalstrom-homeassistant/issues/1 erwähnt. Nach der Ursache muss ich noch suchen. Die aktuellen Logs sind dazu vermutlich nicht hilfreich, am Logging sollte ich auch noch einiges verbessern.

**Comment by Mat931** [comment]
Der Fehler sollte in Version 0.0.5 behoben sein.

**Comment by BA2000** [comment]
Wau, du bist ja schnell.
Hab's gerade auf Version 0.0.5 upgedated. Teste gleich...ja hat funktioniert! Super.

Außerdem ist jetzt die Anzahl der Entitäten von 191 auf 325 gestiegen.

Gruß BA2000 

Am 28. Dezember 2023 21:20:20 MEZ schrieb Mat931 ***@***.***>:

**Comment by Mat931** [comment]
Ja, von den neuen Entitäten haben vermutlich die meisten `Unbekannt` als Wert. Kann leider nicht unterscheiden ob eine Entität dauerhaft oder nur vorübergehend `Unbekannt` ist, also werden jetzt einfach alle hinzugefügt.
