### ISSUE TITLE
Server certificate validation failed

### ISSUE THREAD

**Issue by hakensline** [Mat931/digitalstrom-homeassistant#5]
Hello Mat !

Tanks for your Job !

I want to add your integration to my HA v2023.12.4 but  when HA alone detects my DSS, I enter the user password as well as the fingerprint key

07:97:68:03:29:9C:3A:B5:44:B8:0D:C2:69:B8:CA:F4:C7:92:E7:C8:54:D3:3E:84:88:65:A8:BA:D7:5D:AF:BF

and y have a error message Server certificate validation failed
![Capture d'écran 2023-12-28 171136](https://github.com/Mat931/digitalstrom-homeassistant/assets/755091/ac81b9e0-21b8-42eb-bb85-958098cdd4fe)

You have any ideas for me ? 

My DSS its updated to V 1.19.6.3

Many Tanks

**Comment by Mat931** [comment]
That usually means that the fingerprint does not match the server certificate. Did you follow [these steps](https://github.com/Mat931/digitalstrom-homeassistant/blob/main/certificate_fingerprint.md) to get the fingerprint from the DSS?

**Comment by hakensline** [comment]
Yes exactly but not working. Its not possible to bypass this ?

**Comment by Mat931** [comment]
Not with the current version of this component. I can add an option to bypass it in a future version.

**Comment by hakensline** [comment]
Ok i have reboot my DSS, change password but noway :-(

**Comment by Mat931** [comment]
Okay, I added the option. To try it you need to re-install the integration in HACS, enable "Show beta versions" and select "main" as the version. Then instead of the fingerprint type the word "ignore".

**Comment by hakensline** [comment]
Tanks ! Its work ! Tank you so mutch !!!!

**Comment by hakensline** [comment]
Tanks ! Its work ! Nice job :-)
