### ISSUE TITLE
2 different thermostats / sensor apearing in the same device

### ISSUE THREAD

**Issue by jtognazzi** [Mat931/digitalstrom-homeassistant#6]
Hi,
I just installed your HA integration and it was pretty easy and straightforward to configure, thanks !

But I have a small issue with two of my FTW04 dS room sensors, they both appear in the same device giving me 2 values for temperature and 2 values for humidity.
The other 2 identical sensors are displayed properly in their respective devices...

So, I really have no idea what can be wrong here.
What is really weird is that these 2 sensors are connected to 2 different dSM12.

well, do you have an idea how I could fix that ?

thanks for any hint.

Julien

**Comment by Mat931** [comment]
Hi!
Can you send me a debug log? First make sure you have version 0.0.5 of the digitalSTROM integration installed in [HACS](https://my.home-assistant.io/redirect/hacs_repository/?owner=Mat931&repository=digitalstrom-homeassistant&category=integration). Then enable debug logging [here](https://my.home-assistant.io/redirect/integration/?domain=digitalstrom). Reload the integration or restart Home Assistant. Then disable debug logging to save the log file. If you have Discord you can send me the file there. (@Mat931)

**Comment by jtognazzi** [comment]
Hi,
here is the log file:
[home-assistant_digitalstrom_2024-01-03T08-32-24.252Z.log](https://github.com/Mat931/digitalstrom-homeassistant/files/13817440/home-assistant_digitalstrom_2024-01-03T08-32-24.252Z.log)

The 2 thermostats ending in the same device are:
    "name": "Raumfühler Wohnen" and
    "name": "Raumfühler Till"

**Comment by Mat931** [comment]
The issue should be fixed in version 0.0.6

**Comment by jtognazzi** [comment]
Woah, thanks !
I will test asap.

**Comment by jtognazzi** [comment]
I can confirm that the thermostats are now detected in different devices !
Thank you very much for the very quick fix
