### ISSUE TITLE
Benutzerdefinierte Handlung für Tore als Taster

### ISSUE THREAD

**Issue by 1Nimra** [Mat931/digitalstrom-homeassistant#7]
Hallo,

Wir haben mehrere Tore als Benutzerdefinierte Handlungen angelegt. Leider erscheinen diese nur als Schalter. Gibt es eine Möglichkeit diese in HA als Taster anzulegen? (Bin leider noch totaler Neuling, komme von IOBroker)
![IMG_0681](https://github.com/Mat931/digitalstrom-homeassistant/assets/155881495/8d38ec0a-0d55-489d-9f13-f6e55c13763a)

**Comment by Mat931** [comment]
Hallo!
Ja, die Möglichkeit gibt es. Diese Anleitung bezieht sich auf die neuste Version (2024.1) von Home Assistant.

- Legen Sie in Home Assistant für jedes Tor einen [Helfer](https://my.home-assistant.io/redirect/helpers/) vom Typ "Taste" an.
- Erstellen Sie dann pro Tor eine [Automatisierung](https://my.home-assistant.io/redirect/automations/).
- Wählen Sie als Auslöser den Helfer aus. (Entität -> Zustand, als Entität den Helfer auswählen)
- Fügen Sie als Aktion das Einschalten des digitalSTROM-Schalters hinzu (Schalter -> Einschalten, als Entität den Schalter auswählen).
- Fügen Sie als Aktion eine Wartezeit hinzu (Bausteine -> Warten auf den Ablauf der Zeit), z.B. 1 Sekunde.
- Fügen Sie als Aktion das Ausschalten des digitalSTROM-Schalters hinzu (Schalter -> Ausschalten, als Entität den Schalter auswählen).

**Comment by 1Nimra** [comment]
Hallo, vielen Dank!!Wow, das hat ja perfekt geklappt!Kann man auch Raum-Solltemperaturen ändern?Viele Grüße!Von meinem iPhone gesendetAm 07.01.2024 um 14:43 schrieb Mat931 ***@***.***>:﻿
Hallo!
Ja, die Möglichkeit gibt es. Diese Anleitung bezieht sich auf die neuste Version (2024.1) von Home Assistant.

Legen Sie in Home Assistant für jedes Tor einen Helfer vom Typ "Taste" an.
Erstellen Sie dann pro Tor eine Automatisierung.
Wählen Sie als Auslöser den Helfer aus. (Entität -> Zustand, als Entität den Helfer auswählen)
Fügen Sie als Aktion das Einschalten des digitalSTROM-Schalters hinzu (Schalter -> Einschalten, als Entität den Schalter auswählen).
Fügen Sie als Aktion eine Wartezeit hinzu (Bausteine -> Warten auf den Ablauf der Zeit), z.B. 1 Sekunde.
Fügen Sie als Aktion das Ausschalten des digitalSTROM-Schalters hinzu (Schalter -> Ausschalten, als Entität den Schalter auswählen).

**Comment by Mat931** [comment]
Das Ändern der Temperaturen ist momentan noch nicht möglich und ist für eine zukünftige Version geplant.

**Comment by 1Nimra** [comment]
Von meinem iPhone gesendetAm 09.01.2024 um 21:18 schrieb Armin Leithel ***@***.***>:﻿Hallo,Danke für die Rückmeldung!Mir ist auch noch aufgefallen, dass die Benutzerdefinierten Zustände von DS leider in HA genau verdreht zu denen in Digitalstrom sind:DS zeigt geschlossen, wenn in HA offen und andersherum.Von meinem iPhone gesendetAm 09.01.2024 um 19:23 schrieb Mat931 ***@***.***>:﻿
Closed #7 as completed.

**Comment by Mat931** [comment]
Öffnen Sie bitte dafür ein neues Issue und hängen Sie einen Debug-Log an. Sie können [hier](https://my.home-assistant.io/redirect/integration/?domain=digitalstrom) die Debug-Protokollierung einschalten, anschließend die Integration neu laden und dann die Protokollierung ausschalten um den Log zu erhalten.
