### ISSUE TITLE
Addition control of position of the slats of external blinds

### ISSUE THREAD

**Issue by MCLMNN** [Mat931/digitalstrom-homeassistant#8]
Vielen Dank für die dss-Integration. Endlich kann ich meine Raffstore in Home Assistant sehen/steuern, ohne sie auf ein anderes System umzurüsten. Meine Frage bzw. Bitte bezieht sich auf meine Raffstore. Ich kann sie nun runter und hoch fahren. Nun würde ich gerne auch die Öffnung, also die Stellung der Lamellen, steuern können. Es wäre toll, wenn das noch ergänzt werden würde.

Vielleicht noch ein paar Informationen dazu: es handelt sich um die GR-KL220 Klemme. Sie wird durch einen Taster (1-fach) angesteuert. Bei Betätigung fährt sie abwechselnd hoch oder runter. Beim Hochfahren werden die Lamellen auf offen gestellt, beim Herunterfahren auf geschlossen. Mit der aktuellen Konfiguration deiner Integration schließen sie auch nach dem Hochfahren, was durch ein kurzes Herunterfahren realisiert wird.

**Comment by Mat931** [comment]
Hallo,
die Funktion habe ich hinzugefügt, aber leider kann ich sie selbst nicht testen. Installieren Sie dazu bitte die Version 'main' der digitalSTROM-Integration über HACS und geben Sie mir Rückmeldung ob alles funktioniert oder ob z.B. offen und geschlossen vertauscht sind.
Vielen Dank

**Comment by MCLMNN** [comment]
Hallo, und erst einmal vielen Dank für die schnelle Implementierung. Ich habe über HACS die Version "Main" installiert, also Version 643bf22. Nach einem Neustart kann ich leider kein neues Steuerelement für die Lamellenstellung finden. Es sieht alles unverändert aus. Ich habe sicherheitshalber auch noch mal unter Einstellungen > Integrationen > digitalstrom den Integrationseintrag gelöscht und anschließend meine dss-Anlage wieder gekoppelt. Habe ich etwas übersehen?

**Comment by Mat931** [comment]
Es sollte kein neues Steuerelement erscheinen. Die Lamellensteuerung ist über das bisherige Steuerelement abrufbar. Vielleicht habe ich aber bei der Implementierung etwas übersehen

**Comment by Mat931** [comment]
Okay, bitte nochmal neu installieren

**Comment by MCLMNN** [comment]
Ich habe das gleich mal getestet. Das Steuerelement wurde um die Neigung der Lamellen ergänzt. Die Richtung ist auch korrekt. Allerdings funktioniert die Neigungseinstellung nur über die Pfeiltasten. Beim Verstellen der Neigung über den Slider kommt es zu folgender Fehlermeldung: 

**Fehler beim Aufrufen des Diensts cover/set_cover_tilt_position. name 'ATTR_TILT_POSITION' is not defined**

**Comment by Mat931** [comment]
Thanks for testing! Should be fixed now. If everything works I can release a new version

**Comment by MCLMNN** [comment]
Perfekt. Habe beide Varianten getestet. Die Lamellen werden korrekt geneigt. Danke für die schnelle Umsetzung und die Integration selbst. Ich wollte schon die Hardware tauschen 🙈
